# infrastructure/s3-buckets.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 buckets for lakehouse pipeline'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  
  ProjectName:
    Type: String
    Default: lakehouse-ecommerce

Resources:
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-raw-${Environment}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ProcessedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-processed-${Environment}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-code-${Environment}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

Outputs:
  RawDataBucketName:
    Description: Name of the raw data bucket
    Value: !Ref RawDataBucket
    Export:
      Name: !Sub "${AWS::StackName}-RawDataBucket"
  
  ProcessedDataBucketName:
    Description: Name of the processed data bucket
    Value: !Ref ProcessedDataBucket
    Export:
      Name: !Sub "${AWS::StackName}-ProcessedDataBucket"
